### ISSUE TITLE
how to change the color or something to make it more obvious?

### ISSUE THREAD

**Issue by RedemptionC** [liamcain/obsidian-lapel#24]
.cm-heading-marker[data-level="2"] {
	--background-color: "red";
}

this doesn't work, removing the -- doesn't work either

**Comment by liamcain** [comment]
You can try adding !important

```css
.cm-heading-marker {
	color: red !important;
}
```

This works for me
